### ISSUE TITLE
Get GitHub Issue templates for people to report issues

### ISSUE THREAD

**Issue by karuppiah7890** [alexanderepstein/Insomnia#16]
@alexanderepstein Something like this : https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md

And when people find errors they should be able to land on the Issue Report web page directly from the App with a click, just an easy way for them to reach the page if they aren't coders or techy people.

**Comment by alexanderepstein** [comment]
I definitely agree I should link to report a bug in my code but i am skeptical of adding an issue template. The only reason being i think it detracts some users from submitting a bug because they dont want to take the time to meet the standards of the template

**Comment by alexanderepstein** [comment]
I added a report a bug menu item in the insomnia application.

**Comment by karuppiah7890** [comment]
I get it that many users may not want to submit bugs if the issue template is big and stuff.

But I think you could have a simple issue template, like asking these details : 

Description of bug or feature enhancement : 
OS and OS version : 
Version of Insomnia Application : 

These are basic details that you will however need, which you will ask in comments if you don't get it from user through the template. And trust me, it gets harder to reply to comments when many people start putting up bugs or feature enhancements, though this is just a small application with less use cases

**Comment by alexanderepstein** [comment]
I see what you mean and its a fair point you've convinced me to implement a very loose ruled template

**Comment by alexanderepstein** [comment]
@karuppiah7890 I implemented a very loose version, thanks for the tip
