### ISSUE TITLE
App should remember the sleep time set

### ISSUE THREAD

**Issue by karuppiah7890** [alexanderepstein/Insomnia#17]
When I close the App after setting the sleep time and consequently setting notifications, when I reopen the App, it should open with the time I had set already, but this doesn't happen currently. 

It would be nice to see the already set time when the App is reopened.

**Comment by alexanderepstein** [comment]
The application should open with your default wake up time set to the current wake up time. I was thinking of storing a temp time just in case the preference of the user was different then the time they had chosen for that particular night.

**Comment by karuppiah7890** [comment]
Yes, having user preferences for such stuff should be good. You just have to plan out the UI/UX for this so that it's easy for the user to manage his/her preferences and also know the default settings
