### ISSUE TITLE
Option to choose times for notifications

### ISSUE THREAD

**Issue by manparvesh** [alexanderepstein/Insomnia#18]
I would be great if we can choose the times at which notifications should be displayed.
For example, if I set wake-up time to 7:00 a.m., the notifications start at 9:45 p.m, which seems too early (at least for me). So if I am able to set the notifications to start after, say, 11 pm, it would be better in my opinion.
What do you think?

**Comment by alexanderepstein** [comment]
I could easily implement something like this but I generate 6 optimal sleep times. So if you put this constraint on the application the 6 generates sleep times will remain the same however it would only show a notification for the ones after your set time. Does that still suit your needs?

**Comment by manparvesh** [comment]
Yes, that is exactly I am trying to say. 
Thank you

**Comment by alexanderepstein** [comment]
@manparvesh I will implement this tomorrow. I am going to be releasing a new version that has some automation for the update process built in but still not perfect.
