### ISSUE TITLE
UI/UX Problems and suggestions in Shutdown button in notification

### ISSUE THREAD

**Issue by karuppiah7890** [alexanderepstein/Insomnia#19]
Hey @alexanderepstein 
I think the "Shutdown" button should be renamed as "Shutdown Computer". Just a suggestion. 

And I think it would be better to confirm with the user about shutting down the computer instead of abruptly shutting it down. Why ? because the user might click the wrong button in a hurry or by mistake and this would lead to abrupt shutdown, and he/she might lose any unsaved changes in his files or it stop big file uploads or downloads, at least downloads can sometimes be resumed. It can lead to many other problems.

A confirmation to shutdown is always good. What do you think ?

**Comment by alexanderepstein** [comment]
I think I am going to implement both of your suggestions, I definitely agree it may have been a little risky to just have a shutdown button with no confirmation.

**Comment by alexanderepstein** [comment]
@karuppiah7890 do you think its enough to have it show another notification but with the message 'are you sure you want to shutdown' with the options of yes and no. If you wait to long the notification would assume you meant no.

**Comment by karuppiah7890** [comment]
Yes, that should do! :smile:

**Comment by alexanderepstein** [comment]
@karuppiah7890 implemented in latest commit :) will be available with next release I just have a few more new preferences to add and have to package them for all platforms again.

**Comment by karuppiah7890** [comment]
Cool !
