### ISSUE TITLE
Can we use brew install this APP in Mac?

### ISSUE THREAD

**Issue by johnwatsondev** [alexanderepstein/Insomnia#20]

**Comment by alexanderepstein** [comment]
At the moment no, but I was looking into the idea of making a cask from what I understand though having a package on any major distribution platform subjects it to abunch of heavy constraints about file structure etc...

**Comment by rockchalkwushock** [comment]
@alexanderepstein so when I did:

```bash
brew search insomnia
Caskroom/cask/insomnia # this is not your application?
Caskroom/cask/insomniax
```

**Comment by alexanderepstein** [comment]
If you run that and it's an app that functions like mine maybe someone else got that running for me and didn't let me know but I doubt it.

**Comment by rockchalkwushock** [comment]
Looking like no 👍 

![screen shot 2017-05-01 at 10 41 28 pm](https://cloud.githubusercontent.com/assets/19720404/25603211/621f5502-2ebf-11e7-94a0-7c791d2e8237.png)

**Comment by alexanderepstein** [comment]
Ahh funny enough that's actually another application written in the electron framework named Insomnia and I didn't realize that it existed for a while. Because of that application if mine continues to grow in popularity I will give it a unique name.
