### ISSUE TITLE
Move packages to Github from Dropbox

### ISSUE THREAD

**Issue by sachinkamath** [alexanderepstein/Insomnia#21]
It'd be better to have it here on [Github as releases](https://help.github.com/articles/creating-releases/) so that users don't really have to click on external links to download the binary files.

**Comment by zomars** [comment]
Also...
<img width="582" alt="captura de pantalla 2017-05-02 a las 09 52 51" src="https://cloud.githubusercontent.com/assets/3504472/25626558/22ef644a-2f1d-11e7-81bc-2a5489ee51cd.png">

**Comment by alexanderepstein** [comment]
Ill get right on that... I had no idea i was generating to much traffic

**Comment by alexanderepstein** [comment]
When I tried to add the binaries to the my github release for version 1.2.0 github seems to not even try to upload it would it be easier if created a branch containing the builds and the links will download the file from there?

**Comment by zomars** [comment]
@alexanderepstein do you have any adblockers enabled? That's has disrupted the uploader for me in the past.

**Comment by alexanderepstein** [comment]
Got it sorted out, all future downloads can now be found under their respective release

https://github.com/alexanderepstein/Insomnia/releases/tag/v1.2.0
