### ISSUE TITLE
[Feat] Consider people chronotypes

### ISSUE THREAD

**Issue by luchillo17** [alexanderepstein/Insomnia#22]
Dr. Michael Breus gave a talk in Kwik Conference about Sleep and peoples chronotype, he talks about how each people chronotype affects the actual lenght of the sleep cycle.

According to his research each people cycle has a different lenght based on their Chronotype, some are longer, some shorter, the average is indeed 90 min, with 5 cycles giving an optimal total sleep time of 7.5 hours.

Giving himself as an example, Dr. Michael Breus calculated his optimal total sleep time in 7 hours, while other people have longer cycles and it goes up to 8 hours based on it's Chronotype.

The feature request has 2 parts:
- Allow user to adjust their cycles based on Chronotypes.
- Add a Chronotype test to allow the user to easy and acurately determine their Chronotype.
- (Optional) As the user receives their Chronotype, make info about it available so they can understand better theirs, making planning around it's Chronotype possible.

**Comment by alexanderepstein** [comment]
@luchillo17  This is so cool and i would love to implement this in an upcoming release do you have any links you recommend to learn about chronotypes?

**Comment by luchillo17** [comment]
Truth to be told, i don't, i just recently watched the conference, though i had to buy the conference pack.

The conference was from Jim Kwik (yes that's his name), and he's supposed to be the guru in Master Memory and Accelerated Learning, and Dr. Michael Breus was talking about how sleep affects brain performance on memory, learning and thinking.

Since i bought the conference i don't know if it's ok to paste here the link to my Google Drive where i keep a copy to watch it in my tablet, but maybe to your mail would be ok, what do you think?

**Comment by alexanderepstein** [comment]
@luchillo17 I did look into this, it is hard to find an algorithm that i could implement myself to determine this trait. Although the quiz exists online I'm not sure how the answers end up with a result. So this would be hard to implement while keeping it inside of my application ex. without sending you to your browser to take the quiz online somewhere else and enter the results back into the application

**Comment by luchillo17** [comment]
I'm digging on it and it seems there's many models of such quiz, though deciding which one works better is the real issue here, those quizzes and their result are most of them open in science papers, though the one made by Dr. Michael Breus can't find it, most likely i'll have to buy the book, and even then i don't think the actual quiz scoring strategy is there.
