### ISSUE TITLE
[RFC] Add how to generate binaries from source in the docs

### ISSUE THREAD

**Issue by zomars** [alexanderepstein/Insomnia#23]
I've never used electron before, so a little how-to would be nice.

**Comment by alexanderepstein** [comment]
Yeah i can add to the readme sometime today :)

**Comment by alexanderepstein** [comment]
Added in commit cc841dea97d05233ee4d48684a5dd3ac7178f5a1

**Comment by zomars** [comment]
nice! Thank you!
