### ISSUE TITLE
CSS/Bootstrap

### ISSUE THREAD

**Issue by alexanderepstein** [alexanderepstein/Insomnia#3]
At the moment I've been utilizing inline HTML styling this should be transferred over to a CSS file and implemented.

**Comment by kaushikpraveen** [comment]
Hi, I would really like to to help out with this issue.
I can prepare the CSS file for all the inline styling.

**Comment by alexanderepstein** [comment]
@kaushikpraveen that would be so awesome! If your up for it fork this repository and do all your work on your repo and when youre done submit a pull request and i will merge it over to the master branch.

**Comment by alexanderepstein** [comment]
@kaushikpraveen If you know anything about bootstrap I was thinking of implementing some of those stylings for my buttons and input fields so if that makes sense to you/is of interest to you having a bootstrap implementation would be awesome.

**Comment by brunopulis** [comment]
I suggest revising the semantics and accessibility as well. This issue I can look =)

**Comment by kaushikpraveen** [comment]
Forked it, will submit the pull request soon.
Yes, I can implement Bootstrap on button & Input fields if you want.

**Comment by alexanderepstein** [comment]
@kaushikpraveen Looks like someone already started to work on a transfer of html inline styling over to css https://github.com/priscilamtzfraire/Insomnia/commit/91910fbdbb965e8f3e0e742a9a204171a86e44c7 However i still would really love a bootstrap implementation to clean up the U.I., maybe you two could work together on accomplishing this.

**Comment by alexanderepstein** [comment]
@brunopulis I dont even truly know what that means but it sounds like something involving html and css that im probably going to want. Like i said in previous comment someone has started the move from html to css so if  what you're talking about requires these files wait until the PR is submitted and pulled over to the master branch.

**Comment by brunopulis** [comment]
@alexanderepstein OK I wait the PR

**Comment by priscilamtzfraire** [comment]
I already finished the CSS part, but I think it would be awesome to have an option for themes or something similar. Let me know your thoughts about this :)

**Comment by alexanderepstein** [comment]
@priscilamtzfraire  I do think that would be pretty cool althgough I'm not sure if id would be very good at implementing it. Also would you mind adding back your version of the about page I liked it a lot more than the dialog and i was sad to see it go with the merge resolve

**Comment by alexanderepstein** [comment]
@priscilamtzfraire by the way i love how the application looks now thank you so much for all your work so far

**Comment by alexanderepstein** [comment]
@priscilamtzfraire I actually was able to figure out how to add back your about.html setup :)

**Comment by alexanderepstein** [comment]
@brunopulis its all good to go for you to add the semantics and accessibility

**Comment by kaushikpraveen** [comment]
@priscilamtzfraire I agree with Alex, you've done a great job converting the css code.👍
@alexanderepstein If its fully done, Shall I go & implement the Bootstrap part if its still needed?

**Comment by alexanderepstein** [comment]
@kaushikpraveen do you think bootstrap is still necessary? Im not quite sure, but if you think it will further improve the U.I. Id love to see it happen

**Comment by priscilamtzfraire** [comment]
Thank you guys! It was great to read your comments. This is a cool project and I wanted to work on it to make it better. I'll be around to see If I can be of assistance

**Comment by brunopulis** [comment]
@priscilamtzfraire  It was very well organized CSS congratulations, I would recommend only to change the ID manipulation by CLASS :)

**Comment by brunopulis** [comment]
@alexanderepstein I think I could use a lighter library than Bootstrap, for example:

* [Bulma](http://bulma.io/)
* [PureCSS](https://purecss.io/)

**Comment by alexanderepstein** [comment]
@brunopulis Those both look pretty cool I didn't even know other bootstrap like libraries existed. If you wanted to fork the new code and implement what you have just described that would be awesome. maybe @kaushikpraveen can help out if its required

**Comment by alexanderepstein** [comment]
I am beyond satisfied with the current GUI and the ability for me to add new elements to each page is beyond simple thanks so much @priscilamtzfraire
