### ISSUE TITLE
[bug] notification

### ISSUE THREAD

**Issue by CharlonTank** [alexanderepstein/Insomnia#33]
**Issue Label:** [Bug,Feature,Enhancement]
BUG

**Description of bug or feature enhancement:**
The notification : "Your computer need a break" shows up like 100 times instantly

**OS and OS version:**
OS X EL CAPITAN 10.11.6

**Version of Insomnia Application:**
1.2.0

sometimes it's like this :
![screen shot 2017-05-04 at 20 59 14](https://cloud.githubusercontent.com/assets/4601603/25720291/a101b5e0-310c-11e7-864e-ed8fc31cc7f1.png)
but sometimes its even worse : my screen become full of notifications in less than 2 seconds, and I need to quit Insomia...

**Comment by alexanderepstein** [comment]
Try updating to 1.3.0 and let me know if that still occurs
