### ISSUE TITLE
Application Provides Break Notification Out of Sync With Time

### ISSUE THREAD

**Issue by northern11** [alexanderepstein/Insomnia#35]
**Issue Label:** [Bug,Feauture,Enhancement]
Notification at the Wrong Time

**Description of bug or feature enhancement:**
I set my time to wake up at 6:30am the next day at 12:05 PM today and then closed the app, but the app has two notifications pop up every 2 minutes or so saying my computer needs a break with the option to dismiss or restart.  

I installed the application last night and set a time in it and went to sleep, however when I woke up there were 20+notifications and I had to force close the application to clear it.

**OS and OS version:**
Windows 10

**Version of Insomnia Application:**
Insomnia Version 1.4.1
Node.js Version 7.4.0
Chromium Version 56.0.2924.87
Electron Version 1.6.6

**Comment by alexanderepstein** [comment]
I have noticed this as well it stems from not shutting down the computer when you go to bed (an assumption I made) although I found I don't really do this either. I've already thought of a fix that includes maximizing the duration of the notification to infinity (you have to click on it, swipe right or click dismiss for it to go away) which will allow me to make sure only one notification of each type can be showing at a time. This will not get rid of the problem but when opening your computer after resting the most notifications you will ever see is 3. Hopefully that's small enough to prevent the need of a force restart.

**Comment by northern11** [comment]
You are correct that it happened probably cause I didnt shut my computer
off. The infinity time on the notification sounds like a good fix.

The other issue was the program did not reset itself for the next day. I
tried to use the program for today and it was still notifying me for
yesterday I think cause 2 notifications were popping up every 2 minutes so
I had to shut it off.

**Comment by alexanderepstein** [comment]
Were they rest notifications? That shouldn't happen the way the scheduling works is it uses an exact date not a time so notifications for yesterday should never show up today.

**Comment by northern11** [comment]
I am not sure if they were actually from yesterday or not. I just assumed
because I have not shut off my computer since I installed the app last
night. They seemed to happen after I set my wakeup time for tomorrow. It
was a little annoying that two notifications would show up as well to "
Dismiss" or "Restart."

**Comment by alexanderepstein** [comment]
I also made sure only one notification of that type should show up. I hope this commit  29f0eb9f100b3e832561e6554adff0ec484a1982 works out all the kinks you described above. It seems to work with the rest notification and should work with the uptime notification as well. I also reset the new sleep times of the day one hour after your last possible rest notification.

**Comment by northern11** [comment]
I just ran the app and set it again and I'm not getting any notifications
like before.

**Comment by alexanderepstein** [comment]
Are you using the version i just pushed or the the application version of 1.4.1?

**Comment by northern11** [comment]
1.4.1 right now. No automatic updates right? When installing yesterday your
download link didnt work for a second, but you must have been updating. How
do I enact the recent update?

**Comment by alexanderepstein** [comment]
Your bug that i hopefully fixed will be version 1.4.2 it hasn't been released yet. I was curious if you were running my application through the electron framework. Hopefully ill have the update released by tonight

**Comment by northern11** [comment]
I dont know what electron framework is so can't say. Thanks for providing
this app. I have shift work starting next week so I'm hoping this can help
me get good sleep even in weird hours

On May 6, 2017 1:35 PM, "Alex Epstein" <notifications@github.com> wrote:

Your bug that i hopefully fixed will be version 1.4.2 it hasn't been
released yet. I was curious if you were running my application through the
electron framework. Hopefully ill have the update released by tonight

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexanderepstein/Insomnia/issues/35#issuecomment-299654809>,
or mute the thread

**Comment by alexanderepstein** [comment]
@northern11 I hope it helps as well! Version 1.4.2 was just released with the bugfixes mentioned in this thread
