### ISSUE TITLE
No System Tray Icon

### ISSUE THREAD

**Issue by nicholaslgoodman** [alexanderepstein/Insomnia#36]
**Issue Label:** [Bug]

**Description of bug or feature enhancement:**
Note: libappindicator1 is installed. I even tried reinstalling it.

There is no system tray icon. Minimizing the program just makes it disappear into the background. (As an aside, this generates three processes, two with absurdly long names.)

**OS and OS version:**
Ubuntu 17.04

**Version of Insomnia Application:**
1.4.1 (same behavior on 1.2.0)
I'm using the dpkg 64-bit version. I see no way to run the version cloned from git.

**Comment by alexanderepstein** [comment]
This seems to be a bug specific to libappindicator not working with the new DE found on Ubuntu 17 this what I found as a workaround http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html

**Comment by nicholaslgoodman** [comment]
Thank you. I was able to fix the issue following those instructions.

**Comment by alexanderepstein** [comment]
@nicholaslgoodman Glad to hear it
