### ISSUE TITLE
[Bug] Unordered optimal sleeping times

### ISSUE THREAD

**Issue by luchillo17** [alexanderepstein/Insomnia#38]
**Issue Label:** [Bug]

**Description of bug or feature enhancement:**
The optimal sleeping times are unordered, is hard to look when your next optimal sleep time is.

**Version of Insomnia Application:**
1.4.2

**Demonstration:**
To show it in order should show 19:45, 21:15, 22:45, 00:15, 01:45 and 02:45 (which might be wrong since intervals were switching between 15 and 45 except 2:45 one).
![image](https://cloud.githubusercontent.com/assets/9698639/25776742/0aa559a8-328d-11e7-9271-280bf510d095.png)

**Comment by alexanderepstein** [comment]
This definitely showed up with me resetting the times one hour after last notification. As you can see the first element is only an hour away from the last rather than an hour and 30 mins away. I will fix this and have a new release up tomorrow

**Comment by alexanderepstein** [comment]
@luchillo17 fixed in latest commit new release will be up tomorrow
