### ISSUE TITLE
Add Native Notifications As Setting

### ISSUE THREAD

**Issue by alexanderepstein** [alexanderepstein/Insomnia#9]
https://www.npmjs.com/package/node-notifier

**Comment by alexanderepstein** [comment]
Dont think i like this idea anymore if somebody does comment on this and i might implement for the hell of it

**Comment by hjri** [comment]
notifications look horrendous on KDE and out of place, not following global settings for notifications

**Comment by alexanderepstein** [comment]
@hjri I'm not sure if you just hate the way my notifications look or if they specifically look different on your environment. If i use native notifications i don't get to assign buttons to the notification.
